AllCops:
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,setup,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
